(* Generated by ocaml-tree-sitter. *)
(*
   crystal grammar

   entrypoint: expressions
*)

open! Sexplib.Conv
open Tree_sitter_run

type binary_double_star = Token.t

type regular_if_keyword = Token.t

type instance_var = Token.t

type operator_token = [
    `PLUS of Token.t (* "+" *)
  | `DASH of Token.t (* "-" *)
  | `STAR of Token.t (* "*" *)
  | `SLASH of Token.t (* "/" *)
  | `SLASHSLASH of Token.t (* "//" *)
  | `PERC of Token.t (* "%" *)
  | `AMP of Token.t (* "&" *)
  | `BAR of Token.t (* "|" *)
  | `HAT of Token.t (* "^" *)
  | `STARSTAR of Token.t (* "**" *)
  | `GTGT of Token.t (* ">>" *)
  | `LTLT of Token.t (* "<<" *)
  | `EQEQ of Token.t (* "==" *)
  | `BANGEQ of Token.t (* "!=" *)
  | `LT of Token.t (* "<" *)
  | `LTEQ of Token.t (* "<=" *)
  | `GT of Token.t (* ">" *)
  | `GTEQ of Token.t (* ">=" *)
  | `LTEQGT of Token.t (* "<=>" *)
  | `EQEQEQ of Token.t (* "===" *)
  | `LBRACKRBRACK of Token.t (* "[]" *)
  | `LBRACKRBRACKQMARK of Token.t (* "[]?" *)
  | `LBRACKRBRACKEQ of Token.t (* "[]=" *)
  | `BANG of Token.t (* "!" *)
  | `TILDE of Token.t (* "~" *)
  | `BANGTILDE of Token.t (* "!~" *)
  | `EQTILDE of Token.t (* "=~" *)
  | `AMPPLUS of Token.t (* "&+" *)
  | `AMPDASH of Token.t (* "&-" *)
  | `AMPSTAR of Token.t (* "&*" *)
  | `AMPSTARSTAR of Token.t (* "&**" *)
]

type unary_wrapping_plus = Token.t

type modifier_unless_keyword = Token.t

type regular_rescue_keyword = Token.t

type block_ampersand = Token.t

type char_escape_sequence = Token.t

type imm_tok_choice_0b_rep_pat_78bc49d_choice_choice_u8 = Token.t

type modifier_rescue_keyword = Token.t

type modifier_if_keyword = Token.t

type anon_opt_COMMA_opt_DOTDOTDOT_0392b4d =
  (Token.t (* "," *) * Token.t (* "..." *) option) option

type pat_a84aa85 = Token.t (* pattern \s* *)

type keyword_named_argument_name = Token.t

type semgrep_ellipsis = Token.t

type heredoc_end = Token.t

type implicit_object_method_operator = Token.t

type unary_star = Token.t

type class_var = Token.t

type pseudo_constant = [
    `X___LINE__ of Token.t (* "__LINE__" *)
  | `X___END_LINE__ of Token.t (* "__END_LINE__" *)
  | `X___FILE__ of Token.t (* "__FILE__" *)
  | `X___DIR__ of Token.t (* "__DIR__" *)
]

type start_of_named_tuple_type = Token.t

type modifier_ensure_keyword = Token.t

type imm_tok_pat_245b2d0 = Token.t (* pattern \\. *)

type symbol_array_percent_literal_start = Token.t

type macro_delimiter_end = Token.t

type end_of_with_expression = Token.t

type heredoc_body_start = Token.t

type implicit_object_method_identifier = Token.t

type start_of_named_tuple = Token.t

type anon_choice_DOTDOT_ed078ec = [
    `DOTDOT of Token.t (* ".." *)
  | `DOTDOTDOT of Token.t (* "..." *)
]

type regular_ensure_keyword = Token.t

type binary_wrapping_minus = Token.t

type implicit_object_ivar = Token.t

type imm_tok_pat_dcdac4f = Token.t (* pattern \s *)

type type_field_colon = Token.t

type semgrep_metavariable = Token.t

type binary_ampersand = Token.t

type binary_wrapping_plus = Token.t

type binary_slash = Token.t

type macro_delimiter_else = Token.t

type pat_5eb9c21 = Token.t (* pattern :\s *)

type constant_segment = Token.t

type imm_tok_squot = Token.t (* "'" *)

type regular_unless_keyword = Token.t

type heredoc_start = Token.t

type imm_tok_lpar = Token.t (* "(" *)

type tok_perc_pat_fdcd585_rep_pat_fdcd585 = Token.t

type line_continuation_explicit = unit (* blank *)

type macro_verbatim_keyword = (
    Token.t (* "{%" *) * Token.t (* "verbatim" *) * Token.t (* "do" *)
  * Token.t (* "%}" *)
)

type modulo_operator = Token.t

type anon_choice_prop_94a3794 = [
    `Prop_1a8db4c of Token.t (* "property" *)
  | `Prop_b128b0f of Token.t (* "property?" *)
]

type special_variable = Token.t

type imm_tok_choice_choice_pat_b628393_rep_pat_6c14acd_pat_b591095_rep_pat_6c14acd_choice_pat_e_choice_choice_pat_dece469_rep1_pat_6c14acd_choice_choice_f32 =
  Token.t

type global_match_data_index = Token.t

type string_array_percent_literal_start = Token.t

type regex_modifier = Token.t

type start_of_symbol = Token.t

type binary_minus = Token.t

type command_literal_end = Token.t

type binary_double_slash = Token.t

type imm_tok_lcurl = Token.t (* "{" *)

type heredoc_content = Token.t

type pat_6ebc02d = Token.t (* pattern abstract\sstruct *)

type identifier_method_call = Token.t

type string_percent_literal_start = Token.t

type identifier_assign = Token.t

type unary_wrapping_minus = Token.t

type unary_double_star = Token.t

type tok_choice_choice_pat_b628393_rep_pat_6c14acd_pat_b591095_rep_pat_6c14acd_choice_pat_e_choice_choice_pat_dece469_rep1_pat_6c14acd_choice_choice_f32 =
  Token.t

type start_of_parenless_args = Token.t

type start_of_tuple_type = Token.t

type pointer_star = Token.t

type start_of_hash_or_tuple = Token.t

type tok_choice_0b_rep_pat_78bc49d_choice_choice_u8 = Token.t

type tok_prec_p1_hashlcurl = Token.t

type delimited_array_element_start = Token.t

type ignored_backslash = Token.t

type line_continuation_explicit_ = unit (* blank *)

type percent_array_escape_sequence = Token.t (* pattern \\[\s})\]>|] *)

type start_of_index_operator = Token.t

type identifier = Token.t

type line_continuation = Token.t

type command_percent_literal_start = Token.t

type imm_tok_qmark = Token.t (* "?" *)

type pat_b22a502 = Token.t (* pattern abstract\sclass *)

type imm_tok_slash = Token.t (* "/" *)

type unquoted_symbol_content = Token.t

type regex_start = Token.t

type start_of_macro_var_exps = Token.t

type string_escape_sequence = Token.t

type imm_tok_prec_p1_pat_ab3dea2 = Token.t (* pattern [^\\/] *)

type binary_star = Token.t

type string_literal_end = Token.t

type imm_tok_colon = Token.t (* ":" *)

type imm_tok_prec_p1_pat_f2207b3 = Token.t (* pattern "[^\\\\\"]+" *)

type end_of_range = Token.t

type macro_begin_keyword = (
    Token.t (* "{%" *) * Token.t (* "begin" *) * Token.t (* "%}" *)
)

type unary_minus = Token.t

type unary_plus = Token.t

type imm_tok_prec_p1_pat_e77da7f = Token.t (* pattern [^\\] *)

type macro_start = Token.t

type command_literal_start = Token.t

type delimited_array_element_end = Token.t

type imm_tok_choice_plus = Token.t

type macro_content_nesting = Token.t

type macro_delimiter_elsif = Token.t

type string_literal_start = Token.t

type macro_content = Token.t

type percent_literal_end = Token.t

type start_of_brace_block = Token.t

type delimited_string_contents = Token.t

type imm_tok_dquot = Token.t (* "\"" *)

type line_break = Token.t

type regex_percent_literal_start = Token.t

type empty_parens = (Token.t (* "(" *) * Token.t (* ")" *))

type line_continuation_explicit2 = unit (* blank *)

type anon_choice_RBRACK_57c1d11 = [
    `RBRACK of Token.t (* "]" *)
  | `RBRACKQMARK of Token.t (* "]?" *)
]

type binary_plus = Token.t

type macro_end_keyword = (
    macro_delimiter_end (*tok*) * Token.t (* "end" *) * Token.t (* "%}" *)
)

type anon_choice_impl_obj_meth_id_3a9d445 = [
    `Impl_obj_meth_id of implicit_object_method_identifier (*tok*)
  | `Impl_obj_meth_op of implicit_object_method_operator (*tok*)
]

type macro_else_keyword = (
    macro_delimiter_else (*tok*) * Token.t (* "else" *) * Token.t (* "%}" *)
)

type forall = (
    Token.t (* "forall" *)
  * constant_segment (*tok*)
  * (Token.t (* "," *) * constant_segment (*tok*)) list (* zero or more *)
)

type block_body_param = [
    `Semg_meta of semgrep_metavariable (*tok*)
  | `Id of identifier (*tok*)
  | `Unde of Token.t (* "_" *)
]

type anon_choice_unde_76e38d1 = [
    `Unde of Token.t (* "_" *)
  | `Id of identifier (*tok*)
]

type anon_choice_id_684e964 = [
    `Id of identifier (*tok*)
  | `Semg_meta of semgrep_metavariable (*tok*)
]

type block_body_splat_param = (
    Token.t (* "*" *)
  * [
        `Id of identifier (*tok*)
      | `Semg_meta of semgrep_metavariable (*tok*)
      | `Unde of Token.t (* "_" *)
    ]
)

type anon_choice_id_0dd119e = [
    `Id of identifier (*tok*)
  | `Id_meth_call of identifier_method_call (*tok*)
  | `Else of Token.t (* "else" *)
  | `Then of Token.t (* "then" *)
  | `Ensure of Token.t (* "ensure" *)
  | `Rescue of Token.t (* "rescue" *)
]

type anon_choice_id_910ec16 = [
    `Id of identifier (*tok*)
  | `Id_meth_call of identifier_method_call (*tok*)
  | `Id_assign of identifier_assign (*tok*)
]

type unquoted_symbol = (
    start_of_symbol (*tok*) * unquoted_symbol_content (*tok*)
)

type anon_choice_un_minus_07c71f0 = [
    `Un_minus of unary_minus (*tok*)
  | `Un_plus of unary_plus (*tok*)
]

type char = (
    Token.t (* "'" *)
  * [
        `Imm_tok_prec_p1_pat_e77da7f of imm_tok_prec_p1_pat_e77da7f
      | `Char_esc_seq of char_escape_sequence (*tok*)
    ]
  * imm_tok_squot (*tok*)
)

type operator_symbol = (start_of_symbol (*tok*) * imm_tok_choice_plus)

type percent_literal_array_word = (
    delimited_array_element_start (*tok*)
  * [
        `Deli_str_content of delimited_string_contents (*tok*)
      | `Perc_array_esc_seq of percent_array_escape_sequence (*tok*)
    ]
      list (* zero or more *)
  * delimited_array_element_end (*tok*)
)

type quoted_symbol = (
    Token.t (* ":\"" *)
  * [
        `Imm_tok_prec_p1_pat_f2207b3 of imm_tok_prec_p1_pat_f2207b3
      | `Str_esc_seq of string_escape_sequence (*tok*)
      | `Igno_back of ignored_backslash (*tok*)
    ]
      list (* zero or more *)
  * imm_tok_dquot (*tok*)
)

type terminator = [
    `Line_brk of line_break (*tok*)
  | `SEMI of Token.t (* ";" *)
]

type regex_literal_content_ =
  [
      `Imm_tok_prec_p1_pat_ab3dea2 of imm_tok_prec_p1_pat_ab3dea2
    | `Imm_tok_pat_245b2d0 of imm_tok_pat_245b2d0
    | `Line_cont_expl2 of line_continuation_explicit2 (*tok*)
  ]
    list (* one or more *)

type anon_choice_blk_body_param_95e3ea5 = [
    `Blk_body_param of block_body_param
  | `Blk_body_splat_param of block_body_splat_param
  | `Blk_body_nested_param of block_body_nested_param
]

and block_body_nested_param = (
    Token.t (* "(" *)
  * anon_choice_blk_body_param_95e3ea5
  * (Token.t (* "," *) * anon_choice_blk_body_param_95e3ea5)
      list (* zero or more *)
  * Token.t (* "," *) option
  * Token.t (* ")" *)
)

type global_method = (Token.t (* "::" *) * anon_choice_id_910ec16)

type float_ = [
    `Choice_un_minus_imm_tok_choice_choice_pat_b628393_rep_pat_6c14acd_pat_b591095_rep_pat_6c14acd_choice_pat_e_choice_choice_pat_dece469_rep1_pat_6c14acd_choice_choice_f32 of (
        anon_choice_un_minus_07c71f0
      * imm_tok_choice_choice_pat_b628393_rep_pat_6c14acd_pat_b591095_rep_pat_6c14acd_choice_pat_e_choice_choice_pat_dece469_rep1_pat_6c14acd_choice_choice_f32
    )
  | `Tok_choice_choice_pat_b628393_rep_pat_6c14acd_pat_b591095_rep_pat_6c14acd_choice_pat_e_choice_choice_pat_dece469_rep1_pat_6c14acd_choice_choice_f32 of
      tok_choice_choice_pat_b628393_rep_pat_6c14acd_pat_b591095_rep_pat_6c14acd_choice_pat_e_choice_choice_pat_dece469_rep1_pat_6c14acd_choice_choice_f32
]

type integer = [
    `Choice_un_minus_imm_tok_choice_0b_rep_pat_78bc49d_choice_choice_u8 of (
        anon_choice_un_minus_07c71f0
      * imm_tok_choice_0b_rep_pat_78bc49d_choice_choice_u8
    )
  | `Tok_choice_0b_rep_pat_78bc49d_choice_choice_u8 of
      tok_choice_0b_rep_pat_78bc49d_choice_choice_u8
]

type string_array_percent_literal = (
    string_array_percent_literal_start (*tok*)
  * percent_literal_array_word list (* zero or more *)
  * percent_literal_end (*tok*)
)

type symbol_array_percent_literal = (
    symbol_array_percent_literal_start (*tok*)
  * percent_literal_array_word list (* zero or more *)
  * percent_literal_end (*tok*)
)

type anon_choice_quoted_symb_22fc626 = [
    `Quoted_symb of quoted_symbol
  | `Unqu_symb of unquoted_symbol
  | `Op_symb of operator_symbol
]

type anon_choice_then_eac33c8 = [
    `Then of Token.t (* "then" *)
  | `Term of terminator
]

type anon_choice_blk_body_param_c57f2a9 = [
    `Blk_body_param of block_body_param
  | `Blk_body_splat_param of block_body_splat_param
  | `Semg_ellips of semgrep_ellipsis (*tok*)
  | `Blk_body_nested_param of block_body_nested_param
]

type pseudo_responds_to_argument_list = [
    `LPAR_choice_quoted_symb_RPAR of (
        Token.t (* "(" *) * anon_choice_quoted_symb_22fc626
      * Token.t (* ")" *)
    )
  | `Choice_quoted_symb of anon_choice_quoted_symb_22fc626
]

type block_param_list = (
    anon_choice_blk_body_param_c57f2a9
  * (Token.t (* "," *) * anon_choice_blk_body_param_c57f2a9)
      list (* zero or more *)
  * Token.t (* "," *) option
)

type abstract_method_def = (
    Token.t (* "abstract" *)
  * base_method_def
  * terminator option
)

and additive_operator = (
    expression
  * [
        `Bin_plus of binary_plus (*tok*)
      | `Bin_minus of binary_minus (*tok*)
      | `Bin_wrap_plus of binary_wrapping_plus (*tok*)
      | `Bin_wrap_minus of binary_wrapping_minus (*tok*)
    ]
  * expression
)

and alias = (
    Token.t (* "alias" *) * constant * Token.t (* "=" *) * bare_type
)

and alignof = (
    Token.t (* "alignof" *) * Token.t (* "(" *) * bare_type
  * Token.t (* ")" *)
)

and and_ = (expression * Token.t (* "&&" *) * expression)

and annotation = (
    Token.t (* "@[" *)
  * constant
  * annotation_argument_list option
  * Token.t (* "]" *)
)

and annotation_argument_list = (
    Token.t (* "(" *)
  * bracket_argument_list option
  * Token.t (* ")" *)
)

and anon_choice_arg_list_with_parens_and_blk_422157f = [
    `Arg_list_with_parens_and_blk of argument_list_with_parens_and_block
  | `Arg_list_no_parens_with_blk of argument_list_no_parens_with_block
]

and anon_choice_bare_type_7b27a0b = [
    `Bare_type of bare_type
  | `Nume_type of numeric_type
]

and anon_choice_choice_unde_01ec478 = [
    `Choice_unde of anon_choice_unde_ca3943d
  | `Lhs_splat of lhs_splat
]

and anon_choice_cst_092cda1 = [
    `Cst of constant
  | `Self of Token.t (* "self" *)
  | `Gene_inst_type of generic_instance_type
]

and anon_choice_cst_10f7578 = [
    `Cst of constant
  | `Nume_type of numeric_type
  | `Type_param_splat of (Token.t (* "*" *) * constant)
]

and anon_choice_cst_6df303a = [
    `Cst of constant
  | `Gene_inst_type of generic_instance_type
]

and anon_choice_cst_segm_3c2ec99 = [
    `Cst_segm of constant_segment (*tok*)
  | `Macro_inte_cst_segm of (constant_segment (*tok*) * macro_expression)
]

and anon_choice_dot_call_efe6367 = [
    `Dot_call of (
        expression
      * Token.t (* "." *)
      * [
            `Id of identifier (*tok*)
          | `Semg_meta of semgrep_metavariable (*tok*)
          | `Cst of constant
          | `Id_meth_call of identifier_method_call (*tok*)
          | `Op_tok of operator_token
          | `Inst_var of instance_var (*tok*)
        ]
    )
  | `Id_meth_call of identifier_method_call (*tok*)
  | `Global_meth of global_method
]

and anon_choice_elsif_b9e1083 = [
    `Elsif of (
        Token.t (* "elsif" *)
      * expression
      * terminator
      * then_ option
      * anon_choice_elsif_b9e1083 option
    )
  | `Else of else_
]

and anon_choice_exp_1124375 = [
    `Exp of expression
  | `Splat of splat
  | `Double_splat of double_splat
  | `Named_expr of named_expr
  | `Out of out
]

and anon_choice_exp_373cb08 = [ `Exp of expression | `Out of out ]

and anon_choice_exp_5f47da4 = [
    `Exp of expression
  | `Impl_obj_call of implicit_object_call
  | `Impl_obj_tuple of (
        start_of_hash_or_tuple (*tok*)
      * (
            expression
          * (Token.t (* "," *) * expression) list (* zero or more *)
          * Token.t (* "," *)
        )
          option
      * [
            `Impl_obj_call of implicit_object_call
          | `Unde of Token.t (* "_" *)
        ]
      * (
            Token.t (* "," *)
          * [
                `Exp of expression
              | `Impl_obj_call of implicit_object_call
              | `Unde of Token.t (* "_" *)
            ]
        )
          list (* zero or more *)
      * Token.t (* "," *) option
      * Token.t (* "}" *)
    )
]

and anon_choice_exp_e0308bd = [
    `Exp of expression
  | `Prop_id of Token.t (* "property" *)
  | `Splat of splat
  | `Double_splat of double_splat
  | `Named_expr of named_expr
  | `Out of out
]

and anon_choice_fun_param_49d118d = [
    `Fun_param of fun_param
  | `Type of type_
]

and anon_choice_id_2655c0e = [
    `Id of identifier (*tok*)
  | `Semg_meta of semgrep_metavariable (*tok*)
  | `Id_meth_call of identifier_method_call (*tok*)
  | `Inst_var of instance_var (*tok*)
  | `Class_var of class_var (*tok*)
  | `Macro_var of macro_var
]

and anon_choice_id_5969394 = [
    `Id of identifier (*tok*)
  | `Cst of constant
  | `Str of string_
]

and anon_choice_id_c52dafb = [
    `Id of identifier (*tok*)
  | `Semg_meta of semgrep_metavariable (*tok*)
  | `Inst_var of instance_var (*tok*)
  | `Class_var of class_var (*tok*)
  | `Macro_var of macro_var
]

and anon_choice_id_df17f27 = [
    `Id of identifier (*tok*)
  | `Id_meth_call of identifier_method_call (*tok*)
  | `Cst of constant
]

and anon_choice_macro_elsif_8f09864 = [
    `Macro_elsif of (
        macro_elsif_cond
      * macro_content_ list (* zero or more *)
      * anon_choice_macro_elsif_8f09864 option
    )
  | `Macro_else of macro_else
]

and anon_choice_param_1e36750 = [
    `Param of param
  | `Splat_param of (
        annotation list (* zero or more *)
      * Token.t (* "*" *)
      * anon_choice_id_c52dafb option
      * (type_field_colon (*tok*) * bare_type) option
    )
  | `Double_splat_param of (
        annotation list (* zero or more *)
      * Token.t (* "**" *)
      * anon_choice_id_c52dafb
      * (type_field_colon (*tok*) * bare_type) option
    )
  | `Semg_ellips of semgrep_ellipsis (*tok*)
]

and anon_choice_semg_meta_de6d985 = [
    `Semg_meta of semgrep_metavariable (*tok*)
  | `Cst of constant
  | `Gene_inst_type of generic_instance_type
]

and anon_choice_semg_meta_ed0b729 = [
    `Semg_meta of semgrep_metavariable (*tok*)
  | `Cst of constant
  | `Gene_type of generic_type
]

and anon_choice_unde_ca3943d = [
    `Unde of Token.t (* "_" *)
  | `Id of identifier (*tok*)
  | `Semg_meta of semgrep_metavariable (*tok*)
  | `Inst_var of instance_var (*tok*)
  | `Class_var of class_var (*tok*)
  | `Macro_var of macro_var
  | `Assign_call of assign_call
  | `Index_call of index_call
  | `Index_op of index_operator
]

and argument_list_no_parens = (
    start_of_parenless_args (*tok*) option
  * anon_choice_exp_1124375
  * (Token.t (* "," *) * anon_choice_exp_1124375) list (* zero or more *)
)

and argument_list_no_parens_with_block = (
    start_of_parenless_args (*tok*) option
  * (
        anon_choice_exp_1124375
      * (Token.t (* "," *) * anon_choice_exp_1124375) list (* zero or more *)
      * Token.t (* "," *)
    )
      option
  * block_argument
)

and argument_list_with_parens = (
    imm_tok_lpar (*tok*)
  * (
        anon_choice_exp_e0308bd
      * (Token.t (* "," *) * anon_choice_exp_e0308bd) list (* zero or more *)
      * Token.t (* "," *) option
    )
      option
  * Token.t (* ")" *)
)

and argument_list_with_parens_and_block = (
    imm_tok_lpar (*tok*)
  * (
        anon_choice_exp_e0308bd
      * (Token.t (* "," *) * anon_choice_exp_e0308bd) list (* zero or more *)
      * Token.t (* "," *)
    )
      option
  * block_argument
  * Token.t (* ")" *)
)

and array_ = [
    `LBRACK_exp_rep_COMMA_exp_opt_COMMA_RBRACK_opt_of_bare_type of (
        Token.t (* "[" *)
      * expression
      * (Token.t (* "," *) * expression) list (* zero or more *)
      * Token.t (* "," *) option
      * Token.t (* "]" *)
      * (Token.t (* "of" *) * bare_type) option
    )
  | `LBRACK_RBRACK_of_bare_type of (
        Token.t (* "[" *) * Token.t (* "]" *) * Token.t (* "of" *)
      * bare_type
    )
]

and array_like = (anon_choice_cst_6df303a * tuple)

and asm = (
    Token.t (* "asm" *)
  * Token.t (* "(" *)
  * string_
  * asm_outputs option
  * Token.t (* ")" *)
)

and asm_clobbers = (
    Token.t (* ":" *)
  * asm_clobbers_ option
  * asm_options option
)

and asm_clobbers_ = (
    string_
  * (Token.t (* "," *) * string_) list (* zero or more *)
)

and asm_inputs = (
    Token.t (* ":" *)
  * asm_operands option
  * asm_clobbers option
)

and asm_operand = (
    string_ * Token.t (* "(" *) * expression * Token.t (* ")" *)
)

and asm_operands = (
    asm_operand
  * (Token.t (* "," *) * asm_operand) list (* zero or more *)
)

and asm_options = (Token.t (* ":" *) * asm_options_ option)

and asm_options_ = (
    string_
  * (Token.t (* "," *) * string_) list (* zero or more *)
)

and asm_outputs = (
    Token.t (* ":" *)
  * asm_operands option
  * asm_inputs option
)

and assign = (
    [
        `Unde of Token.t (* "_" *)
      | `Id of identifier (*tok*)
      | `Prop of Token.t (* "property" *)
      | `Semg_meta of semgrep_metavariable (*tok*)
      | `Inst_var of instance_var (*tok*)
      | `Class_var of class_var (*tok*)
      | `Macro_var of macro_var
      | `Assign_call of assign_call
      | `Index_call of index_call
      | `Index_op of index_operator
      | `Spec_var of special_variable (*tok*)
    ]
  * Token.t (* "=" *)
  * [ `Exp of expression | `Prop_id of Token.t (* "property" *) ]
)

and assign_call = (expression * Token.t (* "." *) * identifier (*tok*))

and bare_type = [
    `Proc_type of (
        splattable_type
      * (Token.t (* "," *) * splattable_type) list (* zero or more *)
      * Token.t (* "->" *)
      * type_ option
    )
  | `Spla_type of splattable_type
]

and base_fun_def = (
    Token.t (* "fun" *)
  * [
        `Id of identifier (*tok*)
      | `Id_meth_call of identifier_method_call (*tok*)
    ]
  * (Token.t (* "=" *) * anon_choice_id_5969394) option
  * (Token.t (* "(" *) * fun_param_list option * Token.t (* ")" *)) option
  * (type_field_colon (*tok*) * bare_type) option
)

and base_method_def = (
    Token.t (* "def" *)
  * (
        [
            `Semg_meta of semgrep_metavariable (*tok*)
          | `Cst of constant
          | `Self of Token.t (* "self" *)
        ]
      * Token.t (* "." *)
    )
      option
  * [
        `Id of identifier (*tok*)
      | `Semg_meta of semgrep_metavariable (*tok*)
      | `Id_meth_call of identifier_method_call (*tok*)
      | `Id_assign of identifier_assign (*tok*)
      | `Op_tok of operator_token
      | `BQUOT of Token.t (* "`" *)
    ]
  * (Token.t (* "(" *) * param_list option * Token.t (* ")" *)) option
  * (type_field_colon (*tok*) * bare_type) option
  * forall option
)

and begin_ = (
    Token.t (* "begin" *)
  * terminator option
  * statements option
  * rescue_else_ensure option
  * Token.t (* "end" *)
)

and beginless_range = (
    anon_choice_DOTDOT_ed078ec
  * end_of_range (*tok*) option
  * expression option
)

and binary_and_operator = (
    expression * binary_ampersand (*tok*) * expression
)

and binary_or_operator = (
    expression
  * [ `BAR of Token.t (* "|" *) | `HAT of Token.t (* "^" *) ]
  * expression
)

and block_argument = (
    block_ampersand (*tok*)
  * [ `Exp of expression | `Impl_obj_call of implicit_object_call ]
)

and block_param = (
    annotation list (* zero or more *)
  * Token.t (* "&" *)
  * anon_choice_id_c52dafb option
  * (pat_5eb9c21 * bare_type) option
)

and brace_block = (
    start_of_brace_block (*tok*)
  * (Token.t (* "|" *) * block_param_list * Token.t (* "|" *)) option
  * statements option
  * Token.t (* "}" *)
)

and bracket_argument_list = (
    anon_choice_exp_1124375
  * (Token.t (* "," *) * anon_choice_exp_1124375) list (* zero or more *)
  * Token.t (* "," *) option
)

and c_struct_expression = [
    `Macro_node of macro_node
  | `Incl of include_
  | `C_struct_fields of (
        identifier (*tok*)
      * (Token.t (* "," *) * identifier (*tok*)) list (* zero or more *)
      * type_field_colon (*tok*)
      * bare_type
    )
]

and c_struct_expressions = [
    `Rep1_choice_c_struct_exp_term_opt_c_struct_exp of (
        [
            `C_struct_exp_term of (c_struct_expression * terminator)
          | `SEMI of Token.t (* ";" *)
        ]
          list (* one or more *)
      * c_struct_expression option
    )
  | `C_struct_exp of c_struct_expression
]

and call = [
    `Choice_dot_call_opt_choice_arg_list_with_parens of (
        anon_choice_dot_call_efe6367
      * control_expressions option
    )
  | `Choice_id_choice_arg_list_with_parens of (
        anon_choice_id_684e964 * control_expressions
    )
  | `Macro_exp_arg_list_with_parens of (
        macro_expression * argument_list_with_parens
    )
  | `Choice_prop_prop_arg_list of (
        anon_choice_prop_94a3794 * property_argument_list
    )
  | `Choice_prop_prop_arg_list_brace_blk of (
        anon_choice_prop_94a3794 * property_argument_list * brace_block
    )
  | `Choice_prop_arg_list_with_parens of (
        anon_choice_prop_94a3794 * argument_list_with_parens
    )
  | `Choice_prop_arg_list_with_parens_brace_blk of (
        anon_choice_prop_94a3794 * argument_list_with_parens * brace_block
    )
  | `Choice_dot_call_opt_choice_arg_list_with_parens_brace_blk of (
        anon_choice_dot_call_efe6367
      * control_expressions option
      * brace_block
    )
  | `Choice_id_opt_choice_arg_list_with_parens_brace_blk of (
        anon_choice_id_684e964
      * control_expressions option
      * brace_block
    )
  | `Choice_dot_call_opt_choice_arg_list_with_parens_do_end_blk of (
        anon_choice_dot_call_efe6367
      * control_expressions option
      * do_end_block
    )
  | `Choice_id_opt_choice_arg_list_with_parens_do_end_blk of (
        anon_choice_id_684e964
      * control_expressions option
      * do_end_block
    )
  | `Choice_dot_call_choice_arg_list_with_parens_and_blk of (
        anon_choice_dot_call_efe6367
      * anon_choice_arg_list_with_parens_and_blk_422157f
    )
  | `Choice_id_choice_arg_list_with_parens_and_blk of (
        anon_choice_id_684e964
      * anon_choice_arg_list_with_parens_and_blk_422157f
    )
]

and case = (
    Token.t (* "case" *)
  * expression option
  * when_ list (* zero or more *)
  * else_ option
  * Token.t (* "end" *)
)

and chained_string = (string_ * string_ list (* one or more *))

and class_def = (
    Token.t (* "abstract" *) option
  * Token.t (* "class" *)
  * anon_choice_semg_meta_ed0b729
  * (Token.t (* "<" *) * anon_choice_semg_meta_de6d985) option
  * statements option
  * Token.t (* "end" *)
)

and class_type = (type_ * Token.t (* "." *) * Token.t (* "class" *))

and command = (
    command_literal_start (*tok*)
  * string_literal_content option
  * command_literal_end (*tok*)
)

and command_percent_literal = (
    command_percent_literal_start (*tok*)
  * string_percent_literal_content option
  * percent_literal_end (*tok*)
)

and comparison_operator = (
    expression
  * [
        `LT of Token.t (* "<" *)
      | `LTEQ of Token.t (* "<=" *)
      | `GT of Token.t (* ">" *)
      | `GTEQ of Token.t (* ">=" *)
      | `LTEQGT of Token.t (* "<=>" *)
    ]
  * expression
)

and complement_operator = (Token.t (* "~" *) * expression)

and conditional = (
    expression * Token.t (* "?" *) * expression * Token.t (* ":" *)
  * expression
)

and const_assign = (constant * Token.t (* "=" *) * statement)

and constant = (
    Token.t (* "::" *) option
  * anon_choice_cst_segm_3c2ec99
  * (Token.t (* "::" *) * anon_choice_cst_segm_3c2ec99)
      list (* zero or more *)
)

and control_expressions = [
    `Arg_list_with_parens of argument_list_with_parens
  | `Arg_list_no_parens of argument_list_no_parens
]

and do_end_block = (
    Token.t (* "do" *)
  * (Token.t (* "|" *) * block_param_list * Token.t (* "|" *)) option
  * statements option
  * rescue_else_ensure option
  * Token.t (* "end" *)
)

and double_splat = (unary_double_star (*tok*) * expression)

and else_ = (Token.t (* "else" *) * statements option)

and ensure = (regular_ensure_keyword (*tok*) * statements option)

and enum_def = (
    Token.t (* "enum" *)
  * constant
  * (pat_5eb9c21 * bare_type) option
  * enum_statements option
  * Token.t (* "end" *)
)

and enum_statement = [
    `Macro_node of macro_node
  | `Cst of constant
  | `Const_assign of const_assign
  | `Meth_def of method_def
  | `Macro_def of macro_def
  | `Class_var of class_var (*tok*)
  | `Class_var_assign of (class_var (*tok*) * Token.t (* "=" *) * statement)
  | `Anno of annotation
  | `Visi_modi of visibility_modifier
]

and enum_statements = [
    `Rep1_choice_enum_stmt_term_opt_enum_stmt of (
        [
            `Enum_stmt_term of (enum_statement * terminator)
          | `SEMI of Token.t (* ";" *)
        ]
          list (* one or more *)
      * enum_statement option
    )
  | `Enum_stmt of enum_statement
]

and equality_operator = (
    expression
  * [
        `EQEQ of Token.t (* "==" *)
      | `BANGEQ of Token.t (* "!=" *)
      | `EQTILDE of Token.t (* "=~" *)
      | `BANGTILDE of Token.t (* "!~" *)
      | `EQEQEQ of Token.t (* "===" *)
    ]
  * expression
)

and exhaustive_case = (
    Token.t (* "case" *)
  * expression
  * in_ list (* one or more *)
  * Token.t (* "end" *)
)

and exponential_operator = (
    expression
  * [
        `Bin_double_star of binary_double_star (*tok*)
      | `AMPSTARSTAR of Token.t (* "&**" *)
    ]
  * expression
)

and expression = [
    `Semg_meta of semgrep_metavariable (*tok*)
  | `Semg_ellips of semgrep_ellipsis (*tok*)
  | `Deep_ellips of (
        Token.t (* "<..." *) * expression * Token.t (* "...>" *)
    )
  | `Choice_macro_node of [
        `Macro_node of macro_node
      | `Nil of Token.t (* "nil" *)
      | `True of Token.t (* "true" *)
      | `False of Token.t (* "false" *)
      | `Int of integer
      | `Float of float_
      | `Char of char
      | `Array of array_
      | `Hash of hash
      | `Str of string_
      | `Chai_str of chained_string
      | `Str_perc_lit of string_percent_literal
      | `Str_array_perc_lit of string_array_percent_literal
      | `Op_symb of operator_symbol
      | `Unqu_symb of unquoted_symbol
      | `Quoted_symb of quoted_symbol
      | `Symb_array_perc_lit of symbol_array_percent_literal
      | `Here_start of heredoc_start (*tok*)
      | `Range of range
      | `Begi_range of beginless_range
      | `Tuple of tuple
      | `Named_tuple of named_tuple
      | `Proc of proc
      | `Meth_proc of method_proc
      | `Cmd of command
      | `Cmd_perc_lit of command_percent_literal
      | `Regex of regex
      | `Regex_perc_lit of regex_percent_literal
      | `Empty_parens of empty_parens
      | `Paren_expres of parenthesized_expressions
      | `Begin of begin_
      | `Self of Token.t (* "self" *)
      | `Cst of constant
      | `Gene_inst_type of generic_instance_type
      | `Nila_cst of nilable_constant
      | `Pseudo_cst of pseudo_constant
      | `Spec_var of special_variable (*tok*)
      | `Global_match_data_index of global_match_data_index (*tok*)
      | `Id of identifier (*tok*)
      | `Inst_var of instance_var (*tok*)
      | `Class_var of class_var (*tok*)
      | `Macro_var of macro_var
      | `Type_decl of type_declaration
      | `While of while_
      | `Until of until
      | `If of if_
      | `Unless of unless
      | `Cond of conditional
      | `Case of case
      | `Exha_case of exhaustive_case
      | `Select of select
      | `Call of call
      | `Addi_op of additive_operator
      | `Un_addi_op of unary_additive_operator
      | `Mult_op of multiplicative_operator
      | `Expo_op of exponential_operator
      | `Shift_op of shift_operator
      | `Comp_op_6e1517d of complement_operator
      | `Bin_and_op of binary_and_operator
      | `Bin_or_op of binary_or_operator
      | `Equa_op of equality_operator
      | `Comp_op_b5e2455 of comparison_operator
      | `Index_op of index_operator
      | `Pseudo_call of pseudo_call
      | `Index_call of index_call
      | `Array_like of array_like
      | `Hash_like of hash_like
      | `Assign of assign
      | `Unin_assign of uninitialized_assign
      | `Op_assign of operator_assign
      | `Not of not
      | `And of and_
      | `Or of or_
      | `Asm of asm
      | `Yield of yield
      | `Typeof of typeof
      | `Poin of pointerof
      | `Sizeof of sizeof
      | `Inst_sizeof of instance_sizeof
      | `Alig of alignof
      | `Inst_alig of instance_alignof
      | `Offs of offsetof
    ]
]

and fun_param = (
    anon_choice_id_df17f27 * type_field_colon (*tok*) * bare_type
)

and fun_param_list = (
    fun_param
  * (Token.t (* "," *) * fun_param) list (* zero or more *)
  * anon_opt_COMMA_opt_DOTDOTDOT_0392b4d
)

and fun_type_param_list = (
    anon_choice_fun_param_49d118d
  * (Token.t (* "," *) * anon_choice_fun_param_49d118d)
      list (* zero or more *)
  * anon_opt_COMMA_opt_DOTDOTDOT_0392b4d
)

and generic_instance_type = (
    constant
  * imm_tok_lpar (*tok*)
  * type_instance_param_list option
  * Token.t (* ")" *)
)

and generic_type = (
    constant
  * imm_tok_lpar (*tok*)
  * type_param_list option
  * Token.t (* ")" *)
)

and global_var = (
    Token.t (* "$" *)
  * identifier (*tok*)
  * (Token.t (* "=" *) * [ `Id of identifier (*tok*) | `Cst of constant ])
      option
  * type_field_colon (*tok*)
  * bare_type
)

and hash = [
    `Start_of_hash_or_tuple_hash_entry_rep_COMMA_hash_entry_opt_COMMA_RCURL_opt_of_bare_type_EQGT_bare_type of (
        start_of_hash_or_tuple (*tok*)
      * hash_entry
      * (Token.t (* "," *) * hash_entry) list (* zero or more *)
      * Token.t (* "," *) option
      * Token.t (* "}" *)
      * (Token.t (* "of" *) * bare_type * Token.t (* "=>" *) * bare_type)
          option
    )
  | `Start_of_hash_or_tuple_RCURL_of_bare_type_EQGT_bare_type of (
        start_of_hash_or_tuple (*tok*) * Token.t (* "}" *)
      * Token.t (* "of" *) * bare_type * Token.t (* "=>" *) * bare_type
    )
]

and hash_entry = (expression * Token.t (* "=>" *) * expression)

and hash_like = (anon_choice_cst_6df303a * hash)

and if_ = (
    regular_if_keyword (*tok*)
  * expression
  * terminator
  * then_ option
  * anon_choice_elsif_b9e1083 option
  * Token.t (* "end" *)
)

and implicit_object_call = [
    `Impl_obj_call_chai of implicit_object_call_chainable
  | `Impl_obj_call_unch of (
        implicit_object_call_chainable option
      * [
            `Choice_impl_obj_meth_id_arg_list_no_parens of (
                anon_choice_impl_obj_meth_id_3a9d445
              * argument_list_no_parens
            )
          | `Choice_impl_obj_meth_id_arg_list_no_parens_with_blk of (
                anon_choice_impl_obj_meth_id_3a9d445
              * argument_list_no_parens_with_block
            )
          | `Choice_impl_obj_meth_id_EQ_arg_list_no_parens of (
                anon_choice_impl_obj_meth_id_3a9d445 * Token.t (* "=" *)
              * argument_list_no_parens
            )
        ]
    )
]

and implicit_object_call_chainable = [
  `Rectype of (
      implicit_object_call_chainable option
    * [
          `Choice_impl_obj_meth_id_opt_arg_list_with_parens of (
              anon_choice_impl_obj_meth_id_3a9d445
            * argument_list_with_parens option
          )
        | `Choice_impl_obj_meth_id_start_of_index_op_brac_arg_list_choice_RBRACK of (
              anon_choice_impl_obj_meth_id_3a9d445
            * start_of_index_operator (*tok*) * bracket_argument_list
            * anon_choice_RBRACK_57c1d11
          )
        | `Choice_impl_obj_meth_id_EQ_arg_list_with_parens of (
              anon_choice_impl_obj_meth_id_3a9d445 * Token.t (* "=" *)
            * argument_list_with_parens
          )
        | `Choice_impl_obj_meth_id_opt_choice_arg_list_with_parens_brace_blk of (
              anon_choice_impl_obj_meth_id_3a9d445
            * control_expressions option
            * brace_block
          )
        | `Choice_impl_obj_meth_id_opt_choice_arg_list_with_parens_do_end_blk of (
              anon_choice_impl_obj_meth_id_3a9d445
            * control_expressions option
            * do_end_block
          )
        | `Choice_impl_obj_meth_id_arg_list_with_parens_and_blk of (
              anon_choice_impl_obj_meth_id_3a9d445
            * argument_list_with_parens_and_block
          )
        | `Impl_obj_ivar of implicit_object_ivar (*tok*)
        | `Impl_obj_index_op of implicit_object_index_operator
      ]
  )
]

and implicit_object_index_operator = (
    Token.t (* "." *) * start_of_index_operator (*tok*)
  * bracket_argument_list * anon_choice_RBRACK_57c1d11
)

and in_ = (
    Token.t (* "in" *)
  * anon_choice_exp_5f47da4
  * (Token.t (* "," *) * anon_choice_exp_5f47da4) list (* zero or more *)
  * anon_choice_then_eac33c8
  * statements option
)

and include_ = (Token.t (* "include" *) * anon_choice_cst_092cda1)

and index_call = (
    expression * Token.t (* "." *) * Token.t (* "[" *)
  * bracket_argument_list * anon_choice_RBRACK_57c1d11
)

and index_operator = (
    expression
  * start_of_index_operator (*tok*)
  * bracket_argument_list option
  * anon_choice_RBRACK_57c1d11
)

and inline_statement = [
    `Modi_if of (statement * modifier_if_keyword (*tok*) * expression)
  | `Modi_unless of (
        statement * modifier_unless_keyword (*tok*) * expression
    )
  | `Modi_rescue of (
        statement * modifier_rescue_keyword (*tok*) * expression
    )
  | `Modi_ensure of (
        statement * modifier_ensure_keyword (*tok*) * expression
    )
  | `Ret of (Token.t (* "return" *) * control_expressions option)
  | `Next of (Token.t (* "next" *) * control_expressions option)
  | `Brk of (Token.t (* "break" *) * control_expressions option)
]

and instance_alignof = (
    Token.t (* "instance_alignof" *) * Token.t (* "(" *) * bare_type
  * Token.t (* ")" *)
)

and instance_sizeof = (
    Token.t (* "instance_sizeof" *) * Token.t (* "(" *) * bare_type
  * Token.t (* ")" *)
)

and interpolation = (
    tok_prec_p1_hashlcurl (*tok*)
  * [ `Exp of expression | `Inline_stmt of inline_statement ]
  * Token.t (* "}" *)
)

and lhs_splat = (Token.t (* "*" *) * anon_choice_unde_ca3943d)

and lib_def = (
    Token.t (* "lib" *)
  * [ `Cst of constant | `Gene_type of generic_type ]
  * lib_statements option
  * Token.t (* "end" *)
)

and lib_statement = [
    `Macro_node of macro_node
  | `Alias of alias
  | `Fun_def of (
        Token.t (* "fun" *)
      * anon_choice_id_df17f27
      * (Token.t (* "=" *) * anon_choice_id_5969394) option
      * (
            line_break (*tok*) option
          * Token.t (* "(" *)
          * fun_type_param_list option
          * Token.t (* ")" *)
        )
          option
      * (type_field_colon (*tok*) * bare_type) option
    )
  | `Type_def of (
        Token.t (* "type" *) * constant * Token.t (* "=" *) * bare_type
    )
  | `C_struct_def of (
        Token.t (* "struct" *) * constant * c_struct_expressions
      * Token.t (* "end" *)
    )
  | `Union_def of (
        Token.t (* "union" *) * constant * union_expressions
      * Token.t (* "end" *)
    )
  | `Enum_def of enum_def
  | `Global_var of global_var
  | `Const_assign of const_assign
  | `Anno of annotation
  | `Visi_modi of visibility_modifier
]

and lib_statements = [
    `Rep1_choice_lib_stmt_term_opt_lib_stmt of (
        [
            `Lib_stmt_term of (lib_statement * terminator)
          | `SEMI of Token.t (* ";" *)
        ]
          list (* one or more *)
      * lib_statement option
    )
  | `Lib_stmt of lib_statement
]

and macro_content_ = [
    `Choice_macro_node of [
        `Macro_node of macro_node
      | `Macro_var of macro_var
      | `Macro_lit_content of macro_literal_content
      | `Term of terminator
    ]
  | `RCURLRCURL of Token.t (* "}}" *)
]

and macro_def = (
    macro_signature
  * macro_start (*tok*)
  * macro_def_content list (* zero or more *) option
  * Token.t (* "end" *)
)

and macro_def_content = [
    `Macro_node of macro_node
  | `Macro_var of macro_var
  | `Macro_def_lit_content of macro_def_literal_content
  | `Term of terminator
]

and macro_def_literal_content = [
    `Str of string_
  | `Macro_content_nest of macro_content_nesting (*tok*)
  | `Choice_pat_b22a502_rep_macro_def_content_end of (
        [
            `Pat_b22a502 of pat_b22a502
          | `Pat_6ebc02d of pat_6ebc02d
          | `Anno of Token.t (* "annotation" *)
          | `Begin of Token.t (* "begin" *)
          | `Case of Token.t (* "case" *)
          | `Class of Token.t (* "class" *)
          | `Def of Token.t (* "def" *)
          | `Do of Token.t (* "do" *)
          | `Enum of Token.t (* "enum" *)
          | `Fun of Token.t (* "fun" *)
          | `If of Token.t (* "if" *)
          | `Lib of Token.t (* "lib" *)
          | `Macro of Token.t (* "macro" *)
          | `Module of Token.t (* "module" *)
          | `Select of Token.t (* "select" *)
          | `Struct of Token.t (* "struct" *)
          | `Union of Token.t (* "union" *)
          | `Unless of Token.t (* "unless" *)
          | `Until of Token.t (* "until" *)
          | `While of Token.t (* "while" *)
        ]
      * macro_def_content list (* zero or more *)
      * Token.t (* "end" *)
    )
]

and macro_else = (
    macro_else_keyword
  * macro_content_ list (* zero or more *)
)

and macro_elsif_cond = (
    macro_delimiter_elsif (*tok*) * Token.t (* "elsif" *) * expression
  * Token.t (* "%}" *)
)

and macro_expression = (
    Token.t (* "{{" *)
  * [
        `Splat of splat
      | `Double_splat of double_splat
      | `Exp of expression
      | `Inline_stmt of inline_statement
    ]
  * Token.t (* "}}" *)
)

and macro_for_expr = (
    Token.t (* "{%" *)
  * Token.t (* "for" *)
  * anon_choice_unde_76e38d1
  * (Token.t (* "," *) * anon_choice_unde_76e38d1) list (* zero or more *)
  * Token.t (* "in" *)
  * [ `Exp of expression | `Splat of splat | `Double_splat of double_splat ]
  * Token.t (* "%}" *)
)

and macro_if_cond = (
    Token.t (* "{%" *) * regular_if_keyword (*tok*) * expression
  * Token.t (* "%}" *)
)

and macro_literal_content = [
    `Str of string_
  | `Macro_content of macro_content (*tok*)
]

and macro_node = [
    `Macro_exp of macro_expression
  | `Macro_stmt of (
        Token.t (* "{%" *)
      * statements option
      * Token.t (* "%}" *)
    )
  | `Macro_begin of (
        macro_begin_keyword
      * macro_content_ list (* zero or more *)
      * macro_end_keyword
    )
  | `Macro_if of (
        macro_if_cond
      * macro_content_ list (* zero or more *)
      * anon_choice_macro_elsif_8f09864 option
      * macro_end_keyword
    )
  | `Macro_unless of (
        macro_unless_cond
      * macro_content_ list (* zero or more *)
      * macro_else option
      * macro_end_keyword
    )
  | `Macro_for of (
        macro_for_expr
      * macro_content_ list (* zero or more *)
      * macro_end_keyword
    )
  | `Macro_verb of (
        macro_verbatim_keyword
      * macro_content_ list (* zero or more *)
      * macro_end_keyword
    )
]

and macro_signature = (
    Token.t (* "macro" *)
  * [
        `Id of identifier (*tok*)
      | `Semg_meta of semgrep_metavariable (*tok*)
      | `Id_meth_call of identifier_method_call (*tok*)
      | `Op_tok of operator_token
      | `BQUOT of Token.t (* "`" *)
    ]
  * [
        `LPAR_opt_param_list_RPAR of (
            Token.t (* "(" *)
          * param_list option
          * Token.t (* ")" *)
        )
      | `Term of terminator
    ]
)

and macro_unless_cond = (
    Token.t (* "{%" *) * regular_unless_keyword (*tok*) * expression
  * Token.t (* "%}" *)
)

and macro_var = (
    tok_perc_pat_fdcd585_rep_pat_fdcd585
  * (
        start_of_macro_var_exps (*tok*) option
      * imm_tok_lcurl (*tok*)
      * expression
      * (Token.t (* "," *) * expression) list (* zero or more *)
      * Token.t (* "," *) option
      * Token.t (* "}" *)
    )
      option
)

and method_def = (
    base_method_def
  * terminator option
  * statements option
  * rescue_else_ensure option
  * Token.t (* "end" *)
)

and method_proc = (
    Token.t (* "->" *)
  * [
        `Choice_id_DOT_choice_id of (
            [
                `Id of identifier (*tok*)
              | `Inst_var of instance_var (*tok*)
              | `Class_var of class_var (*tok*)
              | `Self of Token.t (* "self" *)
              | `Cst of constant
            ]
          * Token.t (* "." *)
          * [
                `Id of identifier (*tok*)
              | `Id_meth_call of identifier_method_call (*tok*)
              | `Id_assign of identifier_assign (*tok*)
              | `Op_tok of operator_token
            ]
        )
      | `Choice_global_meth of [
            `Global_meth of global_method
          | `Choice_id of anon_choice_id_910ec16
        ]
    ]
  * (Token.t (* "(" *) * type_instance_param_list * Token.t (* ")" *)) option
)

and module_def = (
    Token.t (* "module" *)
  * anon_choice_semg_meta_ed0b729
  * statements option
  * Token.t (* "end" *)
)

and multi_assign = [
    `Lhs_splat_EQ_exp of (lhs_splat * Token.t (* "=" *) * expression)
  | `Rep1_choice_choice_unde_COMMA_choice_choice_unde_EQ_exp of (
        (anon_choice_choice_unde_01ec478 * Token.t (* "," *))
          list (* one or more *)
      * anon_choice_choice_unde_01ec478
      * Token.t (* "=" *)
      * expression
    )
  | `Lhs_splat_EQ_rep1_exp_COMMA_exp of (
        lhs_splat
      * Token.t (* "=" *)
      * (expression * Token.t (* "," *)) list (* one or more *)
      * expression
    )
  | `Rep1_choice_choice_unde_COMMA_choice_choice_unde_EQ_rep1_exp_COMMA_exp of (
        (anon_choice_choice_unde_01ec478 * Token.t (* "," *))
          list (* one or more *)
      * anon_choice_choice_unde_01ec478
      * Token.t (* "=" *)
      * (expression * Token.t (* "," *)) list (* one or more *)
      * expression
    )
]

and multiplicative_operator = (
    expression
  * [
        `Bin_star of binary_star (*tok*)
      | `AMPSTAR of Token.t (* "&*" *)
      | `Bin_slash of binary_slash (*tok*)
      | `Bin_double_slash of binary_double_slash (*tok*)
      | `Modulo_op of modulo_operator (*tok*)
    ]
  * expression
)

and named_expr = [
    `Choice_id_imm_tok_colon_choice_exp of (
        [
            `Id of identifier (*tok*)
          | `With of Token.t (* "with" *)
          | `Cst_segm of constant_segment (*tok*)
          | `Id_meth_call of identifier_method_call (*tok*)
          | `Str of string_
          | `Str_perc_lit of string_percent_literal
        ]
      * imm_tok_colon (*tok*)
      * anon_choice_exp_373cb08
    )
  | `Kw_named_arg_name_choice_exp of (
        keyword_named_argument_name (*tok*) * anon_choice_exp_373cb08
    )
]

and named_tuple = (
    start_of_named_tuple (*tok*)
  * named_expr
  * (Token.t (* "," *) * named_expr) list (* zero or more *)
  * Token.t (* "," *) option
  * Token.t (* "}" *)
)

and named_tuple_type = (
    start_of_named_tuple_type (*tok*)
  * named_type
  * (Token.t (* "," *) * named_type) list (* zero or more *)
  * Token.t (* "," *) option
  * Token.t (* "}" *)
)

and named_type = (
    [
        `Id of identifier (*tok*)
      | `Cst_segm of constant_segment (*tok*)
      | `Id_meth_call of identifier_method_call (*tok*)
      | `Str of string_
      | `Str_perc_lit of string_percent_literal
    ]
  * imm_tok_colon (*tok*)
  * bare_type
)

and nilable_constant = (
    [
        `Cst of constant
      | `Nila_cst of nilable_constant
      | `Gene_inst_type of generic_instance_type
    ]
  * imm_tok_qmark (*tok*)
)

and nilable_type = (type_ * Token.t (* "?" *))

and no_args_proc_type = (Token.t (* "->" *) * type_ option)

and not = (Token.t (* "!" *) * expression)

and numeric_type = [
    `Int of integer
  | `Float of float_
  | `Sizeof of sizeof
  | `Inst_sizeof of instance_sizeof
  | `Alig of alignof
  | `Inst_alig of instance_alignof
  | `Offs of offsetof
]

and offsetof = (
    Token.t (* "offsetof" *)
  * Token.t (* "(" *)
  * bare_type
  * Token.t (* "," *)
  * [ `Inst_var of instance_var (*tok*) | `Int of integer ]
  * Token.t (* ")" *)
)

and operator_assign = (
    [
        `Id of identifier (*tok*)
      | `Semg_meta of semgrep_metavariable (*tok*)
      | `Inst_var of instance_var (*tok*)
      | `Class_var of class_var (*tok*)
      | `Macro_var of macro_var
      | `Assign_call of assign_call
      | `Index_call of index_call
      | `Index_op of index_operator
    ]
  * [
        `PLUSEQ of Token.t (* "+=" *)
      | `AMPPLUSEQ of Token.t (* "&+=" *)
      | `DASHEQ of Token.t (* "-=" *)
      | `AMPDASHEQ of Token.t (* "&-=" *)
      | `STAREQ of Token.t (* "*=" *)
      | `AMPSTAREQ of Token.t (* "&*=" *)
      | `SLASHEQ of Token.t (* "/=" *)
      | `SLASHSLASHEQ of Token.t (* "//=" *)
      | `PERCEQ of Token.t (* "%=" *)
      | `BAREQ of Token.t (* "|=" *)
      | `AMPEQ of Token.t (* "&=" *)
      | `HATEQ of Token.t (* "^=" *)
      | `STARSTAREQ of Token.t (* "**=" *)
      | `LTLTEQ of Token.t (* "<<=" *)
      | `GTGTEQ of Token.t (* ">>=" *)
      | `BARBAREQ of Token.t (* "||=" *)
      | `AMPAMPEQ of Token.t (* "&&=" *)
    ]
  * expression
)

and or_ = (expression * Token.t (* "||" *) * expression)

and out = (
    Token.t (* "out" *)
  * [
        `Id of identifier (*tok*)
      | `Inst_var of instance_var (*tok*)
      | `Unde of Token.t (* "_" *)
      | `Macro_var of macro_var
    ]
)

and param = (
    annotation list (* zero or more *)
  * identifier (*tok*) option
  * anon_choice_id_2655c0e
  * (type_field_colon (*tok*) * bare_type) option
  * (Token.t (* "=" *) * expression) option
)

and param_list = [
    `Choice_param_rep_COMMA_choice_param_opt_COMMA_opt_blk_param of (
        anon_choice_param_1e36750
      * (Token.t (* "," *) * anon_choice_param_1e36750)
          list (* zero or more *)
      * (Token.t (* "," *) * block_param option) option
    )
  | `Blk_param of block_param
]

and parenthesized_expressions = (
    Token.t (* "(" *) * statements * Token.t (* ")" *)
)

and parenthesized_proc_type = (
    Token.t (* "(" *)
  * [
        `Spla_type_rep1_COMMA_spla_type_opt_COMMA of (
            splattable_type
          * (Token.t (* "," *) * splattable_type) list (* one or more *)
          * Token.t (* "," *) option
        )
      | `Bare_type_COMMA of (bare_type * Token.t (* "," *))
    ]
  * Token.t (* ")" *)
  * Token.t (* "->" *)
  * type_ option
)

and parenthesized_type = (Token.t (* "(" *) * bare_type * Token.t (* ")" *))

and pointer_type = (type_ * pointer_star (*tok*))

and pointerof = (
    Token.t (* "pointerof" *) * Token.t (* "(" *) * expression
  * Token.t (* ")" *)
)

and proc = (
    Token.t (* "->" *)
  * (Token.t (* "(" *) * proc_param_list option * Token.t (* ")" *)) option
  * (pat_5eb9c21 * bare_type) option
  * [ `Do_end_blk of do_end_block | `Brace_blk of brace_block ]
)

and proc_param_list = (
    param
  * (Token.t (* "," *) * param) list (* zero or more *)
  * Token.t (* "," *) option
)

and property_argument_list = [
    `Type_decl of type_declaration
  | `Kw_type_decl of (
        [
            `Else of Token.t (* "else" *)
          | `Then of Token.t (* "then" *)
          | `Ensure of Token.t (* "ensure" *)
          | `Rescue of Token.t (* "rescue" *)
        ]
      * Token.t (* ":" *)
      * imm_tok_pat_dcdac4f
      * bare_type
      * (Token.t (* "=" *) * expression) option
    )
  | `Prop_assign_decl of (
        anon_choice_id_0dd119e * Token.t (* "=" *) * expression
    )
  | `Prop_bare_decl of anon_choice_id_0dd119e
  | `Unqu_symb of unquoted_symbol
  | `Quoted_symb of quoted_symbol
  | `Op_symb of operator_symbol
]

and pseudo_call = [
    `Opt_exp_DOT_choice_as_pseudo_call_arg_list of (
        (expression * Token.t (* "." *)) option
      * [
            `As of Token.t (* "as" *)
          | `AsQM of Token.t (* "as?" *)
          | `Is_aQMARK of Token.t (* "is_a?" *)
        ]
      * pseudo_call_argument_list
    )
  | `Opt_exp_DOT_nilQ_opt_LPAR_RPAR of (
        (expression * Token.t (* "." *)) option
      * Token.t (* "nil?" *)
      * empty_parens option
    )
  | `Opt_exp_DOT_respos_toQM_pseudo_respos_to_arg_list of (
        (expression * Token.t (* "." *)) option
      * Token.t (* "responds_to?" *)
      * pseudo_responds_to_argument_list
    )
]

and pseudo_call_argument_list = [
    `LPAR_bare_type_RPAR of parenthesized_type
  | `Bare_type of bare_type
]

and range = (
    expression
  * anon_choice_DOTDOT_ed078ec
  * end_of_range (*tok*) option
  * expression option
)

and regex = (
    regex_start (*tok*)
  * regex_literal_content option
  * imm_tok_slash (*tok*)
  * regex_modifier (*tok*) option
)

and regex_literal_content =
  [
      `Interp of interpolation
    | `Regex_lit_content_ of regex_literal_content_
  ]
    list (* one or more *)

and regex_percent_literal = (
    regex_percent_literal_start (*tok*)
  * regex_percent_literal_content option
  * percent_literal_end (*tok*)
  * regex_modifier (*tok*) option
)

and regex_percent_literal_content =
  [
      `Interp of interpolation
    | `Deli_str_content of delimited_string_contents (*tok*)
  ]
    list (* one or more *)

and rescue = (
    regular_rescue_keyword (*tok*)
  * [
        `Id_pat_5eb9c21_bare_type of (
            identifier (*tok*) * pat_5eb9c21 * bare_type
        )
      | `Id of identifier (*tok*)
      | `Bare_type of bare_type
    ]
      option
  * terminator
  * statements option
)

and rescue_else_ensure = [
    `Rep1_rescue_opt_else_opt_ensure of (
        rescue list (* one or more *)
      * else_ option
      * ensure option
    )
  | `Rep_rescue_else_opt_ensure of (
        rescue list (* zero or more *)
      * else_
      * ensure option
    )
  | `Rep_rescue_opt_else_ensure of (
        rescue list (* zero or more *)
      * else_ option
      * ensure
    )
]

and select = (
    Token.t (* "select" *)
  * when_ list (* zero or more *)
  * else_ option
  * Token.t (* "end" *)
)

and shift_operator = (
    expression
  * [ `LTLT of Token.t (* "<<" *) | `GTGT of Token.t (* ">>" *) ]
  * expression
)

and sizeof = (
    Token.t (* "sizeof" *) * Token.t (* "(" *) * bare_type
  * Token.t (* ")" *)
)

and splat = (unary_star (*tok*) * expression)

and splattable_type = [
    `Double_splat_type of (unary_double_star (*tok*) * type_)
  | `Splat_type of (Token.t (* "*" *) * type_)
  | `Type of type_
]

and statement = [
    `Exp of expression
  | `Inline_stmt of inline_statement
  | `Const_assign of const_assign
  | `Multi_assign of multi_assign
  | `Anno of annotation
  | `Anno_def of (
        Token.t (* "annotation" *)
      * constant
      * terminator list (* zero or more *)
      * Token.t (* "end" *)
    )
  | `Module_def of module_def
  | `Class_def of class_def
  | `Struct_def of struct_def
  | `Enum_def of enum_def
  | `Lib_def of lib_def
  | `Alias of alias
  | `Meth_def of method_def
  | `Abst_meth_def of abstract_method_def
  | `Macro_def of macro_def
  | `Top_level_fun_def of (
        base_fun_def
      * statements option
      * Token.t (* "end" *)
    )
  | `Visi_modi of visibility_modifier
  | `Requ of (Token.t (* "require" *) * string_)
  | `Incl of include_
  | `Extend of (Token.t (* "extend" *) * anon_choice_cst_092cda1)
]

and statements = [
    `Rep1_choice_stmt_term_opt_stmt of (
        [
            `Stmt_term of (statement * terminator)
          | `SEMI of Token.t (* ";" *)
        ]
          list (* one or more *)
      * statement option
    )
  | `Stmt of statement
]

and static_array_type = (
    type_
  * start_of_index_operator (*tok*)
  * [ `Cst of constant | `Nume_type of numeric_type ]
  * Token.t (* "]" *)
)

and string_ = (
    string_literal_start (*tok*)
  * string_literal_content option
  * string_literal_end (*tok*)
)

and string_literal_content =
  [
      `Line_cont_expl of line_continuation_explicit (*tok*)
    | `Deli_str_content of delimited_string_contents (*tok*)
    | `Str_esc_seq of string_escape_sequence (*tok*)
    | `Igno_back of ignored_backslash (*tok*)
    | `Interp of interpolation
  ]
    list (* one or more *)

and string_percent_literal = (
    string_percent_literal_start (*tok*)
  * string_percent_literal_content option
  * percent_literal_end (*tok*)
)

and string_percent_literal_content =
  [
      `Deli_str_content of delimited_string_contents (*tok*)
    | `Interp of interpolation
    | `Str_esc_seq of string_escape_sequence (*tok*)
    | `Igno_back of ignored_backslash (*tok*)
  ]
    list (* one or more *)

and struct_def = (
    Token.t (* "abstract" *) option
  * Token.t (* "struct" *)
  * anon_choice_semg_meta_ed0b729
  * (Token.t (* "<" *) * anon_choice_semg_meta_de6d985) option
  * statements option
  * Token.t (* "end" *)
)

and then_ = statements

and tuple = (
    start_of_hash_or_tuple (*tok*)
  * expression
  * (Token.t (* "," *) * expression) list (* zero or more *)
  * Token.t (* "," *) option
  * Token.t (* "}" *)
)

and tuple_type = (
    start_of_tuple_type (*tok*)
  * splattable_type
  * (Token.t (* "," *) * splattable_type) list (* zero or more *)
  * Token.t (* "," *) option
  * Token.t (* "}" *)
)

and type_ = [
    `Semg_meta of semgrep_metavariable (*tok*)
  | `Choice_paren_type of [
        `Paren_type of parenthesized_type
      | `Cst of constant
      | `Gene_inst_type of generic_instance_type
      | `Union_type of union_type
      | `Tuple_type of tuple_type
      | `Named_tuple_type of named_tuple_type
      | `No_args_proc_type of no_args_proc_type
      | `Paren_proc_type of parenthesized_proc_type
      | `Class_type of class_type
      | `Unde of Token.t (* "_" *)
      | `Nila_type of nilable_type
      | `Poin_type of pointer_type
      | `Self of Token.t (* "self" *)
      | `Typeof of typeof
      | `Static_array_type of static_array_type
    ]
]

and type_declaration = (
    anon_choice_id_2655c0e
  * Token.t (* ":" *)
  * imm_tok_pat_dcdac4f
  * bare_type
  * (Token.t (* "=" *) * expression) option
)

and type_instance_param_list = (
    [
        `Choice_bare_type_rep_COMMA_choice_bare_type of (
            anon_choice_bare_type_7b27a0b
          * (Token.t (* "," *) * anon_choice_bare_type_7b27a0b)
              list (* zero or more *)
        )
      | `Named_type_rep_COMMA_named_type of (
            named_type
          * (Token.t (* "," *) * named_type) list (* zero or more *)
        )
    ]
  * Token.t (* "," *) option
)

and type_param_list = (
    anon_choice_cst_10f7578
  * (Token.t (* "," *) * anon_choice_cst_10f7578) list (* zero or more *)
  * Token.t (* "," *) option
)

and typeof = (
    Token.t (* "typeof" *)
  * Token.t (* "(" *)
  * expression
  * (Token.t (* "," *) * expression) list (* zero or more *)
  * Token.t (* "," *) option
  * Token.t (* ")" *)
)

and unary_additive_operator = (
    [
        `Un_plus of unary_plus (*tok*)
      | `Un_minus of unary_minus (*tok*)
      | `Un_wrap_plus of unary_wrapping_plus (*tok*)
      | `Un_wrap_minus of unary_wrapping_minus (*tok*)
    ]
  * expression
)

and uninitialized_assign = (
    [
        `Id of identifier (*tok*)
      | `Semg_meta of semgrep_metavariable (*tok*)
      | `Inst_var of instance_var (*tok*)
      | `Class_var of class_var (*tok*)
      | `Global_var of global_var
      | `Macro_var of macro_var
    ]
  * Token.t (* "=" *)
  * uninitialized_var
)

and uninitialized_var = (Token.t (* "uninitialized" *) * bare_type)

and union_expression = [
    `Incl of include_
  | `Union_fields of (
        identifier (*tok*)
      * (Token.t (* "," *) * identifier (*tok*)) list (* zero or more *)
      * type_field_colon (*tok*)
      * bare_type
    )
]

and union_expressions = [
    `Rep1_choice_union_exp_term_opt_union_exp of (
        [
            `Union_exp_term of (union_expression * terminator)
          | `SEMI of Token.t (* ";" *)
        ]
          list (* one or more *)
      * union_expression option
    )
  | `Union_exp of union_expression
]

and union_type = (type_ * (Token.t (* "|" *) * type_) list (* one or more *))

and unless = (
    regular_unless_keyword (*tok*)
  * expression
  * terminator
  * then_ option
  * else_ option
  * Token.t (* "end" *)
)

and until = (
    Token.t (* "until" *)
  * expression
  * terminator
  * statements option
  * Token.t (* "end" *)
)

and visibility_modifier = (
    [ `Priv of Token.t (* "private" *) | `Prot of Token.t (* "protected" *) ]
  * [
        `Call of call
      | `Module_def of module_def
      | `Class_def of class_def
      | `Struct_def of struct_def
      | `Enum_def of enum_def
      | `Lib_def of lib_def
      | `Meth_def of method_def
      | `Abst_meth_def of abstract_method_def
      | `Macro_def of macro_def
      | `Const_assign of const_assign
      | `Alias of alias
    ]
)

and when_ = (
    Token.t (* "when" *)
  * anon_choice_exp_5f47da4
  * (Token.t (* "," *) * anon_choice_exp_5f47da4) list (* zero or more *)
  * anon_choice_then_eac33c8
  * statements option
)

and while_ = (
    Token.t (* "while" *)
  * expression
  * terminator
  * statements option
  * Token.t (* "end" *)
)

and yield = (
    (Token.t (* "with" *) * expression * end_of_with_expression (*tok*))
      option
  * Token.t (* "yield" *)
  * control_expressions option
)

type expressions = statements option

type nil (* inlined *) = Token.t (* "nil" *)

type beginless_range_operator (* inlined *) = Token.t

type loc_pragma_pop (* inlined *) = Token.t

type underscore (* inlined *) = Token.t (* "_" *)

type loc_pragma_push (* inlined *) = Token.t

type private_ (* inlined *) = Token.t (* "private" *)

type self (* inlined *) = Token.t (* "self" *)

type true_ (* inlined *) = Token.t (* "true" *)

type false_ (* inlined *) = Token.t (* "false" *)

type protected (* inlined *) = Token.t (* "protected" *)

type property_identifier (* inlined *) = Token.t (* "property" *)

type error_recovery (* inlined *) = Token.t

type loc_pragma_location (* inlined *) = Token.t

type comment (* inlined *) = Token.t (* pattern #.* *)

type type_field_separator (* inlined *) = type_field_colon (*tok*)

type dummy_alias0 (* inlined *) = line_continuation (*tok*)

type dummy_alias1 (* inlined *) = line_continuation (*tok*)

type dummy_alias2 (* inlined *) = line_continuation (*tok*)

type property_bare_declaration (* inlined *) = anon_choice_id_0dd119e

type annotation_def (* inlined *) = (
    Token.t (* "annotation" *)
  * constant
  * terminator list (* zero or more *)
  * Token.t (* "end" *)
)

type break (* inlined *) = (
    Token.t (* "break" *)
  * control_expressions option
)

type c_struct_def (* inlined *) = (
    Token.t (* "struct" *) * constant * c_struct_expressions
  * Token.t (* "end" *)
)

type c_struct_fields (* inlined *) = (
    identifier (*tok*)
  * (Token.t (* "," *) * identifier (*tok*)) list (* zero or more *)
  * type_field_colon (*tok*)
  * bare_type
)

type class_var_assign (* inlined *) = (
    class_var (*tok*) * Token.t (* "=" *) * statement
)

type deep_ellipsis (* inlined *) = (
    Token.t (* "<..." *) * expression * Token.t (* "...>" *)
)

type dot_call (* inlined *) = (
    expression
  * Token.t (* "." *)
  * [
        `Id of identifier (*tok*)
      | `Semg_meta of semgrep_metavariable (*tok*)
      | `Cst of constant
      | `Id_meth_call of identifier_method_call (*tok*)
      | `Op_tok of operator_token
      | `Inst_var of instance_var (*tok*)
    ]
)

type double_splat_param (* inlined *) = (
    annotation list (* zero or more *)
  * Token.t (* "**" *)
  * anon_choice_id_c52dafb
  * (type_field_colon (*tok*) * bare_type) option
)

type double_splat_type (* inlined *) = (unary_double_star (*tok*) * type_)

type elsif (* inlined *) = (
    Token.t (* "elsif" *)
  * expression
  * terminator
  * then_ option
  * anon_choice_elsif_b9e1083 option
)

type extend (* inlined *) = (
    Token.t (* "extend" *) * anon_choice_cst_092cda1
)

type fun_def (* inlined *) = (
    Token.t (* "fun" *)
  * anon_choice_id_df17f27
  * (Token.t (* "=" *) * anon_choice_id_5969394) option
  * (
        line_break (*tok*) option
      * Token.t (* "(" *)
      * fun_type_param_list option
      * Token.t (* ")" *)
    )
      option
  * (type_field_colon (*tok*) * bare_type) option
)

type implicit_object_call_unchainable (* inlined *) = (
    implicit_object_call_chainable option
  * [
        `Choice_impl_obj_meth_id_arg_list_no_parens of (
            anon_choice_impl_obj_meth_id_3a9d445 * argument_list_no_parens
        )
      | `Choice_impl_obj_meth_id_arg_list_no_parens_with_blk of (
            anon_choice_impl_obj_meth_id_3a9d445
          * argument_list_no_parens_with_block
        )
      | `Choice_impl_obj_meth_id_EQ_arg_list_no_parens of (
            anon_choice_impl_obj_meth_id_3a9d445 * Token.t (* "=" *)
          * argument_list_no_parens
        )
    ]
)

type implicit_object_tuple (* inlined *) = (
    start_of_hash_or_tuple (*tok*)
  * (
        expression
      * (Token.t (* "," *) * expression) list (* zero or more *)
      * Token.t (* "," *)
    )
      option
  * [ `Impl_obj_call of implicit_object_call | `Unde of Token.t (* "_" *) ]
  * (
        Token.t (* "," *)
      * [
            `Exp of expression
          | `Impl_obj_call of implicit_object_call
          | `Unde of Token.t (* "_" *)
        ]
    )
      list (* zero or more *)
  * Token.t (* "," *) option
  * Token.t (* "}" *)
)

type keyword_type_declaration (* inlined *) = (
    [
        `Else of Token.t (* "else" *)
      | `Then of Token.t (* "then" *)
      | `Ensure of Token.t (* "ensure" *)
      | `Rescue of Token.t (* "rescue" *)
    ]
  * Token.t (* ":" *)
  * imm_tok_pat_dcdac4f
  * bare_type
  * (Token.t (* "=" *) * expression) option
)

type macro_begin (* inlined *) = (
    macro_begin_keyword
  * macro_content_ list (* zero or more *)
  * macro_end_keyword
)

type macro_elsif (* inlined *) = (
    macro_elsif_cond
  * macro_content_ list (* zero or more *)
  * anon_choice_macro_elsif_8f09864 option
)

type macro_for (* inlined *) = (
    macro_for_expr
  * macro_content_ list (* zero or more *)
  * macro_end_keyword
)

type macro_if (* inlined *) = (
    macro_if_cond
  * macro_content_ list (* zero or more *)
  * anon_choice_macro_elsif_8f09864 option
  * macro_end_keyword
)

type macro_interpolated_constant_segment (* inlined *) = (
    constant_segment (*tok*) * macro_expression
)

type macro_statement (* inlined *) = (
    Token.t (* "{%" *)
  * statements option
  * Token.t (* "%}" *)
)

type macro_unless (* inlined *) = (
    macro_unless_cond
  * macro_content_ list (* zero or more *)
  * macro_else option
  * macro_end_keyword
)

type macro_verbatim (* inlined *) = (
    macro_verbatim_keyword
  * macro_content_ list (* zero or more *)
  * macro_end_keyword
)

type modifier_ensure (* inlined *) = (
    statement * modifier_ensure_keyword (*tok*) * expression
)

type modifier_if (* inlined *) = (
    statement * modifier_if_keyword (*tok*) * expression
)

type modifier_rescue (* inlined *) = (
    statement * modifier_rescue_keyword (*tok*) * expression
)

type modifier_unless (* inlined *) = (
    statement * modifier_unless_keyword (*tok*) * expression
)

type next (* inlined *) = (Token.t (* "next" *) * control_expressions option)

type proc_type (* inlined *) = (
    splattable_type
  * (Token.t (* "," *) * splattable_type) list (* zero or more *)
  * Token.t (* "->" *)
  * type_ option
)

type property_assign_declaration (* inlined *) = (
    anon_choice_id_0dd119e * Token.t (* "=" *) * expression
)

type require (* inlined *) = (Token.t (* "require" *) * string_)

type return (* inlined *) = (
    Token.t (* "return" *)
  * control_expressions option
)

type splat_param (* inlined *) = (
    annotation list (* zero or more *)
  * Token.t (* "*" *)
  * anon_choice_id_c52dafb option
  * (type_field_colon (*tok*) * bare_type) option
)

type splat_type (* inlined *) = (Token.t (* "*" *) * type_)

type top_level_fun_def (* inlined *) = (
    base_fun_def
  * statements option
  * Token.t (* "end" *)
)

type type_def (* inlined *) = (
    Token.t (* "type" *) * constant * Token.t (* "=" *) * bare_type
)

type type_param_splat (* inlined *) = (Token.t (* "*" *) * constant)

type union_def (* inlined *) = (
    Token.t (* "union" *) * constant * union_expressions
  * Token.t (* "end" *)
)

type union_fields (* inlined *) = (
    identifier (*tok*)
  * (Token.t (* "," *) * identifier (*tok*)) list (* zero or more *)
  * type_field_colon (*tok*)
  * bare_type
)

type heredoc_body (* inlined *) = (
    heredoc_body_start (*tok*)
  * [
        `Here_content of heredoc_content (*tok*)
      | `Interp of interpolation
      | `Pat_a84aa85_str_esc_seq of (
            pat_a84aa85 * string_escape_sequence (*tok*)
        )
      | `Pat_a84aa85_igno_back of (pat_a84aa85 * ignored_backslash (*tok*))
      | `Line_cont_expl_ of line_continuation_explicit_ (*tok*)
    ]
      list (* zero or more *)
  * heredoc_end (*tok*)
)

type extra = [
    `Line_continuation of Loc.t * line_continuation
  | `Loc_pragma_push of Loc.t * loc_pragma_push
  | `Loc_pragma_pop of Loc.t * loc_pragma_pop
  | `Loc_pragma_location of Loc.t * loc_pragma_location
  | `Comment of Loc.t * comment
  | `Heredoc_body of Loc.t * heredoc_body
]

type extras = extra list
