(library
 (public_name semgrep.engine.tests)
 (name semgrep_engine_tests)
 (wrapped false)
 (libraries
   commons
   kcas_data

   semgrep.core
   semgrep.core_scan
   semgrep.il
   semgrep.engine
   semgrep.targeting
   git_wrapper
 )
 (preprocess
    (pps
      ppx_profiling
      ppx_deriving.show
    )
 )
)
