name: build-test-osx-x86
on:
  push:
    branches:
      - main
      - osx/**
    paths-ignore:
      - '**.md'
  workflow_call:
    inputs:
      use-cache:
        default: true
        description: Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build.
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      use-cache:
        default: true
        description: Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build.
        required: true
        type: boolean

jobs:
  build-core:
    strategy:
      matrix:
        ocaml_version: ['5.3.0']
    runs-on: macos-13-large
    steps:
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # ratchet:actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          submodules: true
      - name: Debug use-cache input
        run: |
          echo "use-cache value: ${{ inputs.use-cache }}"
      - env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
        # if: ${{ inputs.use-cache == 'true' || inputs.use-cache == '' }}
        name: Set GHA cache for OPAM in ~/.opam
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # ratchet:actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-v1-opam-${{ matrix.ocaml_version }}-${{ hashFiles('opam/*.opam') }}
          path: ~/.opam
      - name: Install dependencies
        run: ./scripts/osx-setup-for-release.sh ${{ matrix.ocaml_version }}
      - name: Compile opengrep
        run: opam exec -- make core
      - name: Test opengrep-core
        run: opam exec -- make core-test
      - name: Make artifact for ./bin/opengrep-core
        run: |
          mkdir artifacts

          cp ./bin/opengrep-core artifacts/

          pushd artifacts

          install_name_tool -change \
            /usr/local/opt/zstd/lib/libzstd.1.dylib \
            @loader_path/libzstd.1.dylib \
            opengrep-core

          install_name_tool -change \
            /usr/local/opt/gmp/lib/libgmp.10.dylib \
            @loader_path/libgmp.10.dylib \
            opengrep-core

          install_name_tool -change \
            /usr/local/opt/libev/lib/libev.4.dylib \
            @loader_path/libev.4.dylib \
            opengrep-core

          install_name_tool -change \
            /usr/local/opt/pcre2/lib/libpcre2-8.0.dylib \
            @loader_path/libpcre2-8.0.dylib \
            opengrep-core

          install_name_tool -change \
            /usr/local/opt/pcre/lib/libpcre.1.dylib \
            @loader_path/libpcre.1.dylib \
            opengrep-core

          install_name_tool -change \
            /Users/runner/work/opengrep/opengrep/libs/ocaml-tree-sitter-core/tree-sitter/lib/libtree-sitter.0.dylib \
            @loader_path/libtree-sitter.0.dylib \
            opengrep-core

          install_name_tool -delete_rpath \
            /Users/runner/work/opengrep/opengrep/libs/ocaml-tree-sitter-core/tree-sitter/lib \
            opengrep-core

          # otool -l opengrep-core
          otool -L opengrep-core | grep -v "^\\s*/usr/lib/"

          cp /usr/local/opt/zstd/lib/libzstd.1.dylib .
          cp /usr/local/opt/gmp/lib/libgmp.10.dylib .
          cp /usr/local/opt/libev/lib/libev.4.dylib .
          cp /usr/local/opt/pcre2/lib/libpcre2-8.0.dylib .
          cp /usr/local/opt/pcre/lib/libpcre.1.dylib .
          cp /Users/runner/work/opengrep/opengrep/libs/ocaml-tree-sitter-core/tree-sitter/lib/libtree-sitter.0.dylib .

          popd
          tar czf artifacts.tgz artifacts
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # ratchet:actions/upload-artifact@v4
        with:
          name: opengrep-osx-x86
          path: artifacts.tgz

  build-wheels:
    needs:
      - build-core
    runs-on: macos-13-large
    steps:
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # ratchet:actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          submodules: true
      - uses: actions/download-artifact@b14cf4c92620c250e1c074ab0a5800e37df86765 # ratchet:actions/download-artifact@v4
        with:
          name: opengrep-osx-x86
      - run: |
          tar xvfz artifacts.tgz
          cp artifacts/* cli/src/semgrep/bin
          ./scripts/build-wheels.sh
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # ratchet:actions/upload-artifact@v4
        with:
          name: osx-x86-wheel
          path: cli/dist.zip

  test-wheels:
    needs:
      - build-wheels
    runs-on: macos-13-large
    steps:
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # ratchet:actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/download-artifact@b14cf4c92620c250e1c074ab0a5800e37df86765 # ratchet:actions/download-artifact@v4
        with:
          name: osx-x86-wheel
      - run: unzip dist.zip
      - name: install package
        run: pip3 install dist/*.whl
      - run: opengrep --version
      - name: e2e opengrep-core test
        run: echo '1 == 1' | opengrep -l python -e '$X == $X' -
        shell: bash {0}
