name: build-test-core-x86
on:
  push:
    branches:
      - main
      - linux/**
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_call: null
  workflow_dispatch: null

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:

  build-core:
    strategy:
      matrix:
        ocaml_version: ["5.5.0"]
    runs-on: ubuntu-latest

    steps:
      - name: Make checkout speedy
        run: git config --global fetch.parallel 50

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          submodules: true

      - name: Configure git safedir properly
        run: git config --global --add safe.directory $(pwd)

      - name: Compute OPAM cache fingerprint
        run: ./scripts/opam-cache-fingerprint.sh

      - name: Set GHA cache for OPAM
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # ratchet:actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-v2-opam-${{ matrix.ocaml_version }}-${{ hashFiles('.ci-cache/opam-fingerprint.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-v2-opam-${{ matrix.ocaml_version }}-
          path: _opam

      - name: Set SHOULD_INIT_OPAM based on Cache
        run: |
          if [ -d _opam ]; then
            echo "SHOULD_INIT_OPAM=false" >> $GITHUB_ENV
          fi

      - name: Run build inside container
        run: |
          docker run --rm \
            --volume ${{ github.workspace }}:/workspace \
            --env SHOULD_INIT_OPAM=${{ env.SHOULD_INIT_OPAM }} \
            --env OCAML_VERSION=${{ matrix.ocaml_version }} \
            --workdir /workspace \
            alpine:3.22 \
            sh -c \
            "set -e;
             mkdir -p _opam;
             chown -R root:root /workspace/_opam;
             ./scripts/workflow-build-inside-alpine-container.sh;
             chown -R $(id -u):$(id -g) /workspace/_opam"

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # ratchet:actions/upload-artifact@v4
        with:
          name: opengrep-build-linux-x86
          path: artifacts.tgz

      # A tarball rather than a bare file, so that the executable bit survives
      # the upload.
      - name: Make artifact for ./bin/opengrep
        run: |
          mkdir opengrep
          cp ./bin/opengrep opengrep/
          tar czf opengrep.tgz opengrep

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # ratchet:actions/upload-artifact@v4
        with:
          name: opengrep-linux-x86
          path: opengrep.tgz

  build-test-manylinux-x86:
    needs:
      - build-core
    uses: ./.github/workflows/build-test-manylinux.yml
